// <auto-generated />
namespace App.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class EmailModelValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailModelValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202002260337328_EmailModelValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
